### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by Xephobia** [REDxEYE/io_pragma_engine#1]
getting this in log, using blender 2.82

Traceback (most recent call last):
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_pragma_engine\__init__.py", line 54, in execute
    import_model(str(directory / file.name))
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_pragma_engine\model_import.py", line 203, in import_model
    model.from_file(reader)
  File "C:\Users\xeph\Desktop\app\blender-2.82a-windows64\scripts\addons\io_pragma_engine\PyPragma\wmd\wmd_file.py", line 83, in from_file
    assert 24 < self.version <= MAX_SUPPORTED_VERSION, f"Unsupported model version {self.version}!"
AssertionError: Unsupported model version 20!

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
Error says everything you need to know

**Comment by REDxEYE** [comment]
Models V20 aren't supported and won't be in future

**Comment by Xephobia** [comment]
how i can convert vmd version?

**Comment by REDxEYE** [comment]
re-import model from sources with more up-to-date pragma

**Comment by Xephobia** [comment]
i used the standalone version

**Comment by REDxEYE** [comment]
Use steam version

**Comment by Xephobia** [comment]
i can't because all steam keys are taken
